version: '3'

services:
  electionsDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - electionsDBNet
    ports:
      - 3307:3307
    volumes:
    - electionsDBdata:/var/lib/mysql
  electionsdbmigration:
    image: electionsdbmigration
    environment:
      - DATABASE_URL=electionsDB
    networks:
      - electionsDBNet
  admin:
    image: admin
    environment:
      - DATABASE_URL=electionsDB
    ports:
      - 5001:5001
    networks:
      - electionsDBNet
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redisNet
  zvanicnik:
    image: zvanicnik
    deploy:
      replicas: 3
    environment:
      - DATABASE_URL=electionsDB
    ports:
      - 5002:5002
    networks:
      - redisNet
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=electionsDB
    networks:
      - electionsDBNet
      - redisNet
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - electionsDBNet

volumes:
  electionsDBdata:

networks:
  redisNet:
    driver: overlay
  electionsDBNet:
    #driver: overlay